export const sideBarMenuItems = [
  {
    menuItem: 'Home',
    routeLink: '/dashboard/impact-board',
    routeTo: '/dashboard/impact-board',
    icon: 'assets/images/sidebar/ic_All Companies_white.svg',
    id: 0,
    category: 'dashboard',
    hasSeparator: false,
  },
  {
    menuItem: 'My Pilots',
    routeLink: '/dashboard/my-pilots',
    routeTo: '/dashboard/my-pilots',
    icon: 'assets/images/sidebar/ic_All drones_white.svg',
    id: 1,
    category: 'dashboard',
    hasSeparator: false,
  },
  {
    menuItem: 'Inbox',
    routeLink: '/dashboard/inbox',
    routeTo: '/dashboard/inbox',
    icon: 'assets/images/sidebar/ic_Purpose_white.svg',
    id: 2,
    category: 'dashboard',
    hasSeparator: false,
  },
  {
    menuItem: 'My Team',
    routeLink: '/dashboard/my-team',
    routeTo: '/dashboard/my-team',
    icon: 'assets/images/sidebar/ic_Service Centres_white.svg',
    id: 3,
    category: 'dashboard',
    hasSeparator: false,
  },
  {
    menuItem: 'Add Team Members',
    routeLink: '/dashboard/add-team',
    routeTo: '/dashboard/add-team',
    icon: 'assets/images/sidebar/Work.svg',
    id: 4,
    category: 'teams',
    hasSeparator: true,
  },
];
